# Generated by Django 4.2.13 on 2024-06-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
